server.port=8088

spring.application.name=service-request-service

# MongoDB configuration
spring.data.mongodb.uri=mongodb://10.7.93.19:27017/service_request
spring.main.allow-bean-definition-overriding=true
spring.data.mongodb.database=service_request

# Inter-service REST endpoints
onboarding.service.url=http://10.20.242.239:9092
client.otp.baseUrl=http://10.20.242.239:8081
client.otp.sendOtp =otp/send-otp
client.otp.validateOtp = /validate-otp
# MinIO Storage configuration
minio.endpoint=http://10.7.93.19:7000
minio.bucket=clientportal
minio.access-key=admin
minio.secret-key=bracepl@123

# File upload and retention properties
service-request.file.max-size=10MB
service-request.file.retention-days=30

# CORS settings
frontEndUrl=http://10.20.242.202:3000,http://localhost:3000,http://localhost:5173

external-service.baseUrl = http://10.20.242.239:8082

external-service.searchRm = http