spring.application.name=service-request-service
spring.data.mongodb.uri=mongodb://10.7.93.19:27017/onboarding
spring.main.allow-bean-definition-overriding=true
server.port=8088

# Jackson ISO-8601 Date Formatting
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.default-property-inclusion=non_null

#onboarding.service.url: http://10.7.92.19:9092
onboarding.service.url: http://10.20.242.239:9092
client.otp.baseUrl = http://10.20.242.239:8081
external-service.baseUrl = http://10.20.242.239:9092
external-service.searchRm = /onboarding/api/rms/find
client.otp.searchRm = /onboarding/api/rms/find
client.otp.sendOtp = /otp/send-otp
client.otp.validateOtp = /otp/validate-otp
client.otp.sendTemporaryPassword = /notification/forgot-password

notification.service.base-url = http://10.20.242.239:8085
service.name = BRAC EPL STOCK BROKERAGE LTD
service.logo = logo-photo

minio.endpoint = http://10.7.93.19:7000
minio.bucket = clientportal
minio.access-key = admin
minio.secret-key = bracepl@123

frontEndUrl: http://10.20.242.202:3000,http://localhost:3000,http://localhost:5175