package com.beacepl.service_request_service.entity.account;

public enum AccountStatus {
    PENDING, ACTIVE, REJECTED, PARTIAL, EDIT_REQUIRED, EDITED, WAITING_FOR_VALIDATION, VALIDATED, SETTLEMENT_ACCEPTED, ACCEPTED, INITIATED, PEP_APPROVED, PEP_FLAGGED, REFUNDED,  SUSPENDED, CLOSED

}
